config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  root to: 'home#index'

  get '/auditions-spreadsheet', to: 'auditions#index'
  get '/auditions-spreadsheet-generate', to: 'auditions#update'

  post 'change-season', to: 'home#change_season'

  namespace :api do
    namespace :admin do
      resources :conflicts, only: %i[index update]

      resources :payments, only: %i[index create]
      get 'payments/collected', to: 'payments#collected'
      get 'payments/upcoming', to: 'payments#upcoming'
      get 'payments/latest_venmo', to: 'payments#latest_venmo'

      resources :payment_schedules, only: %i[show update]
      post 'payment_schedules/create-default', to: 'payment_schedules#create_default'
      delete 'payment_schedules/remove-entry', to: 'payment_schedules#remove_entry'
      post 'payment_schedules/add-entry', to: 'payment_schedules#add_entry'

      resources :users, only: %i[index show]

      resources :seasons, only: %i[index]
    end

    namespace :coordinators do
      resources :conflicts, only: %i[index update]
    end

    namespace :inventory do
      resources :categories, only: %i[index create update] do
        resources :items, only: %i[create update show]
      end
    end

    namespace :members do
      resources :payment_intents, only: %i[create]
      resources :calendars, only: %i[index]
    end

    namespace :calendars do
      resources :payment_intents, only: %i[create]
    end

    resources :conflict_statuses, only: %i[index]
    resources :files, only: %i[index show]
  end

  namespace :admin do
    get '/', to: 'dashboard#index', as: 'home'

    resources :calendars, only: :index

    resources :conflicts, except: %i[show destroy]

    get 'payments/upcoming', to: 'payments#upcoming_payments'
    get 'payments/behind-members', to: 'payments#behind_members'
    get 'payments/burndown-chart', to: 'payments#burndown_chart'
    get 'payments/recent', to: 'payments#recent_payments'
    put 'payments/restore/:id', to: 'payments#restore'
    resources :payments

    resources :users

    resources :payment_schedules, only: %i[edit]
  end

  namespace :coordinators do
    get '/', to: 'dashboard#index', as: 'home'
    resources :conflicts, except: %i[show destroy]
  end

  namespace :staff do
    get '/', to: 'dashboard#index', as: 'home'
  end

  namespace :members do
    get '/', to: 'dashboard#index', as: 'home'

    resources :calendars, only: %i[index]
    get 'calendars/download', to: 'calendars#download'

    resources :conflicts, only: %i[new create]

    resources :payments, only: %i[new]
    get 'payments/post_processing', to: 'payments#post_processing'
  end

  namespace :inventory do
    resources :categories, only: %i[index new create] do
      resources :items, only: %i[new create show]
    end

    resources :email_rules, except: %i[show destroy]
  end

  resources :files, only: %i[index]

  get 'settings', to: 'settings#index'
  post 'settings', to: 'settings#update'
  post 'settings-password', to: 'settings#change_password'

  get 'rhythm-converter', to: 'tools#rhythm_converter'
  get 'tarp-canvas', to: 'tools#tarp_canvas'
  get 'tarp-canvas-2026', to: 'tools#tarp_canvas_2026'
  get 'tarp-cc2-2026', to: 'tools#tarp_cc2_2026'
  get 'tarp-cc2-2026-segments', to: 'tools#tarp_cc2_2026_segments'
  get 'tarp-grid-tool', to: 'tools#tarp_grid_tool'
  get 'jersey-2026', to: 'tools#jersey_2026'

  resources :calendars, only: %i[index new create]
  get '/calendars/members', to: 'calendars#members'
  get '/calendars/payment-confirmed', to: 'calendars#confirm_payment'

  resources :whistleblowers, only: %i[index create]

  post 'stripe/webhook', to: 'stripe#webhook'
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  before_action :authenticate_user!

  def index
    render_index
  end

  def update
    if current_user.update(email: params[:email], username: params[:username])
      flash[:success] = 'Your settings have been updated!'
      redirect_to(root_url)
    else
      @settings_errors = current_user.errors.full_messages.join('<br />')
      render_index
    end
  end

  def change_password
    unless current_user.valid_password?(params[:old_password])
      @pw_errors = 'Old password was incorrect'
      render_index
      return
    end

    unless params[:new_password] == params[:new_password_confirmation]
      @pw_errors = 'Password confirmation does not match password'
      render_index
      return
    end

    if current_user.update(password: params[:new_password])
      sign_in(current_user, bypass: true)
      flash[:success] = 'Password updated'

      redirect_to(root_url)
    else
      @pw_errors = current_user.errors.full_messages.join('<br />')
      render_index
    end
  end

  private

  def render_index
    case current_user_role
    when 'admin'
      render 'admin/settings/index'
    when 'coordinator'
      render 'coordinators/settings/index'
    when 'staff'
      render 'staff/settings/index'
    else
      render 'members/settings/index'
    end
  end
end

app/controllers/staff/dashboard_controller.rb
# frozen_string_literal: true

module Staff
  class DashboardController < StaffController
    def index
      @next_event = EventService.next_event(current_season['id'])
      @upcoming_conflicts = Conflict
                            .for_season(current_season['id'])
                            .future_conflicts
                            .where('end_date <= ?', 14.days.from_now)
    end
  end
end

app/controllers/staff_controller.rb
# frozen_string_literal: true

class StaffController < ApplicationController
  before_action :authenticate_user!
  before_action -> { redirect_if_not('staff') }

  layout 'staff'
end

app/views/staff/settings/index.html.erb
<div class="flex flex-col">
  <h1>Settings</h1>
  <h2>Basic Info</h2>
  <%= form_with url: settings_path, method: :post do |f| %>
    <div class="grid grid-cols-5 gap-x-6 gap-y-4">
      <% if @settings_errors %>
        <div class="col-span-5 flex text-red-500 items-center">
          <%= raw(@settings_errors) %>
        </div>
      <% end %>
      <div class="col-span-5 sm:col-span-1 -mb-2 sm:mb-0 flex items-center">
        <%= f.label :username, class: 'input-label' %>
      </div>
      <div class="col-span-5 sm:col-span-4">
        <%= text_field_tag :username, current_user.username, class: 'input-text' %>
      </div>

      <div class="col-span-5 sm:col-span-1 -mb-2 sm:mb-0 flex items-center">
        <%= f.label :email, class: 'input-label' %>
      </div>
      <div class="col-span-5 sm:col-span-4">
        <%= text_field_tag :email, current_user.email, class: 'input-text' %>
      </div>
    </div>

    <div class="my-4 flex flex-row justify-end">
      <%= f.submit class: 'btn-primary btn-lg' %>
    </div>
  <% end %>

  <h2 class="mt-6">Password</h2>
  <%= form_with url: '/settings-password', method: :post do |f| %>
    <div class="grid grid-cols-5 gap-x-6 gap-y-4">
      <% if @pw_errors %>
        <div class="col-span-5 flex text-red-500 items-center">
          <%= raw(@pw_errors) %>
        </div>
      <% end %>
      <div class="col-span-5 sm:col-span-1 -mb-2 sm:mb-0 flex items-center">
        <%= f.label :old_password, class: 'input-label' %>
      </div>
      <div class="col-span-5 sm:col-span-4">
        <%= password_field_tag :old_password, nil, class: 'input-text' %>
      </div>

      <div class="col-span-5 sm:col-span-1 -mb-2 sm:mb-0 flex items-center">
        <%= f.label :new_password, class: 'input-label' %>
      </div>
      <div class="col-span-5 sm:col-span-4">
        <%= password_field_tag :new_password, nil, class: 'input-text' %>
      </div>

      <div class="col-span-5 sm:col-span-1 -mb-2 sm:mb-0 flex items-center">
        <%= f.label :new_password_confirmation, 'Confirm', class: 'input-label' %>
      </div>
      <div class="col-span-5 sm:col-span-4">
        <%= password_field_tag :new_password_confirmation, nil, class: 'input-text' %>
      </div>
    </div>

    <div class="my-4 flex flex-row justify-end">
      <%= f.submit class: 'btn-primary btn-lg' %>
    </div>
  <% end %>
</div>